name: Locato
version: 2.0
main: zerrium.Locato
api-version: 1.13
author: zerrium
commands:
  locato:
    description: Locato commands
    usage: /locato <add/edit/remove/delete/search/status> <place_name>
  whereis:
    description: Locate where a saved specified place is in coordinate
    usage: /whereis <place_name>
    permission: locato.whereis
  shareloc:
    description: Share player's current coordinate and dimension, if no player_destination specified, will broadcast to all players
    usage: /shareloc [player_destination]
    permission: locato.shareloc